/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <fstream>
#include <cstdio>
#include <cstdlib>
#include "app.h"
#include "file/reader.h"
#include "file/template.h"

intire::Process::Process() {
    useListFile(
        /*
        (std::getenv("HOME") == NULL ? "" : std::getenv("HOME")) 
        + std::string("/.config/intire/items.json")
        */
        std::string("items.json")
    );
    items = new file::Reader(listfile);
}

int intire::Process::useListFile(std::string file) {
    std::fstream check = std::fstream(file, std::ios_base::in);
    if (check.fail()) {
        std::printf("[E] intire::Process::useListFile() failed: check.fail() returned true for file %s\n", file.c_str());
        exit(1);
    }
    listfile = file;
    return 0;
}

int main(int argc, char* argv[]) {
    intire::Process* proc = new intire::Process();
    file::Category* hdd = new file::Category("HDD", *(proc->items));
    std::printf("%s\n", hdd->pprint().c_str());
    delete hdd;
    delete proc;
    return 0;
}
